<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'AutoTech GmbH',
                'tax_number' => 'DE245781901',
                'email' => 'office@autotech.example',
                'phone' => '+49 69 12345601',
                'address' => 'Hanauer Landstrasse 120',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60314',
                'country' => 'Germany',
                'notes' => 'Corporate fleet customer.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'RheinMain Logistics GmbH',
                'tax_number' => 'DE318452702',
                'email' => 'contact@rheinmain-logistics.example',
                'phone' => '+49 69 23456702',
                'address' => 'Cargo City Süd 18',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60549',
                'country' => 'Germany',
                'notes' => 'Long-term corporate rental customer.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'Frankfurt Consulting GmbH',
                'tax_number' => 'DE289641503',
                'email' => 'office@frankfurt-consulting.example',
                'phone' => '+49 69 34567803',
                'address' => 'Mainzer Landstrasse 50',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60325',
                'country' => 'Germany',
                'notes' => 'Business travel and executive vehicles.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'EuroTech Solutions GmbH',
                'tax_number' => 'DE374829104',
                'email' => 'fleet@eurotech.example',
                'phone' => '+49 69 45678904',
                'address' => 'Lyoner Strasse 15',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60528',
                'country' => 'Germany',
                'notes' => 'Technology company with regular rentals.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'Global Business Travel GmbH',
                'tax_number' => 'DE421758905',
                'email' => 'booking@gbt.example',
                'phone' => '+49 69 56789005',
                'address' => 'Bockenheimer Landstrasse 80',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60323',
                'country' => 'Germany',
                'notes' => 'Corporate travel management partner.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'Rhein Event Services GmbH',
                'tax_number' => 'DE354821706',
                'email' => 'events@rhein-event.example',
                'phone' => '+49 69 67890106',
                'address' => 'Hanauer Landstrasse 175',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60314',
                'country' => 'Germany',
                'notes' => 'Event transportation and VIP rentals.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'Main Finance AG',
                'tax_number' => 'DE198745307',
                'email' => 'mobility@main-finance.example',
                'phone' => '+49 69 78901207',
                'address' => 'Neue Mainzer Strasse 30',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60311',
                'country' => 'Germany',
                'notes' => 'Executive mobility customer.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'German Trade Partners GmbH',
                'tax_number' => 'DE267531408',
                'email' => 'office@german-trade.example',
                'phone' => '+49 69 89012308',
                'address' => 'Friedrich-Ebert-Anlage 20',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60325',
                'country' => 'Germany',
                'notes' => 'Frequent business rental customer.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'Digital Commerce Europe GmbH',
                'tax_number' => 'DE316842609',
                'email' => 'admin@dce.example',
                'phone' => '+49 69 90123409',
                'address' => 'Zeil 100',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60313',
                'country' => 'Germany',
                'notes' => 'Corporate customer.',
            ],[
                'type' => 'company',
                'first_name' => null,
                'last_name' => null,
                'company_name' => 'Premium Mobility Group GmbH',
                'tax_number' => 'DE438217510',
                'email' => 'fleet@premium-mobility.example',
                'phone' => '+49 69 01234510',
                'address' => 'Taunusanlage 8',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60329',
                'country' => 'Germany',
                'notes' => 'Premium and executive vehicle customer.',
            ],[
                'type' => 'individual',
                'first_name' => 'Thomas',
                'last_name' => 'Müller',
                'company_name' => null,
                'tax_number' => null,
                'email' => 'thomas.mueller@example',
                'phone' => '+49 151 10000011',
                'address' => 'Berger Strasse 25',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60316',
                'country' => 'Germany',
                'notes' => 'Private customer.',
            ],[
                'type' => 'individual',
                'first_name' => 'Anna',
                'last_name' => 'Schneider',
                'company_name' => null,
                'tax_number' => null,
                'email' => 'anna.schneider@example',
                'phone' => '+49 151 10000012',
                'address' => 'Leipziger Strasse 40',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60487',
                'country' => 'Germany',
                'notes' => 'Private customer.',
            ],[
                'type' => 'individual',
                'first_name' => 'Michael',
                'last_name' => 'Weber',
                'company_name' => null,
                'tax_number' => null,
                'email' => 'michael.weber@example',
                'phone' => '+49 151 10000013',
                'address' => 'Kaiserstrasse 55',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60329',
                'country' => 'Germany',
                'notes' => 'Private customer.',
            ],[
                'type' => 'individual',
                'first_name' => 'Laura',
                'last_name' => 'Fischer',
                'company_name' => null,
                'tax_number' => null,
                'email' => 'laura.fischer@example',
                'phone' => '+49 151 10000014',
                'address' => 'Bornheimer Landstrasse 80',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60316',
                'country' => 'Germany',
                'notes' => 'Private customer.',
            ],[
                'type' => 'individual',
                'first_name' => 'Daniel',
                'last_name' => 'Klein',
                'company_name' => null,
                'tax_number' => null,
                'email' => 'daniel.klein@example',
                'phone' => '+49 151 10000015',
                'address' => 'Eschersheimer Landstrasse 110',
                'city' => 'Frankfurt am Main',
                'postal_code' => '60322',
                'country' => 'Germany',
                'notes' => 'Private customer.',
            ],
        ];
        foreach ($customers as $customer) {
            Customer::updateOrCreate(
                ['email' => $customer['email']],
                array_merge($customer, [
                    'is_active' => true,
                ])
            );
        }
    }
}
