<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\VehicleCategory;
use App\Models\Vehicle;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $categories = VehicleCategory::pluck('id', 'slug');
        $vehicles = [
            [
                'category' => 'economy',
                'brand' => 'Volkswagen',
                'model' => 'Polo',
                'year' => 2023,
                'license_plate' => 'F-AC 101',
                'vin' => 'WVWZZZAWZPU000101',
                'color' => 'White',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'mileage' => 28450,
                'daily_rate' => 39.00,
                'status' => 'available',
            ],[
                'category' => 'economy',
                'brand' => 'Toyota',
                'model' => 'Yaris',
                'year' => 2024,
                'license_plate' => 'F-AC 102',
                'vin' => 'VNKKJ3D30RA000102',
                'color' => 'Silver',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 15200,
                'daily_rate' => 45.00,
                'status' => 'rented',
            ],[
                'category' => 'economy',
                'brand' => 'Renault',
                'model' => 'Clio',
                'year' => 2023,
                'license_plate' => 'F-AC 103',
                'vin' => 'VF1RJA00000000103',
                'color' => 'Blue',
                'transmission' => 'manual',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'mileage' => 31800,
                'daily_rate' => 39.00,
                'status' => 'available',
            ],[
                'category' => 'compact',
                'brand' => 'Volkswagen',
                'model' => 'Golf',
                'year' => 2024,
                'license_plate' => 'F-AC 104',
                'vin' => 'WVWZZZCD0RW000104',
                'color' => 'Black',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'mileage' => 12100,
                'daily_rate' => 59.00,
                'status' => 'available',
            ],[
                'category' => 'compact',
                'brand' => 'BMW',
                'model' => '1 Series',
                'year' => 2023,
                'license_plate' => 'F-AC 105',
                'vin' => 'WBA7K31000P000105',
                'color' => 'Black',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'mileage' => 22400,
                'daily_rate' => 69.00,
                'status' => 'reserved',
            ],[
                'category' => 'compact',
                'brand' => 'Audi',
                'model' => 'A3',
                'year' => 2024,
                'license_plate' => 'F-AC 106',
                'vin' => 'WAUZZZGY0RA000106',
                'color' => 'Grey',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'mileage' => 9800,
                'daily_rate' => 72.00,
                'status' => 'available',
            ],[
                'category' => 'business',
                'brand' => 'BMW',
                'model' => '3 Series',
                'year' => 2024,
                'license_plate' => 'F-AC 107',
                'vin' => 'WBA8D11000P000107',
                'color' => 'Black',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'mileage' => 18700,
                'daily_rate' => 89.00,
                'status' => 'rented',
            ],[
                'category' => 'business',
                'brand' => 'Mercedes-Benz',
                'model' => 'C-Class',
                'year' => 2024,
                'license_plate' => 'F-AC 108',
                'vin' => 'W1K2060001A000108',
                'color' => 'Silver',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 14300,
                'daily_rate' => 99.00,
                'status' => 'available',
            ],[
                'category' => 'business',
                'brand' => 'Audi',
                'model' => 'A4',
                'year' => 2023,
                'license_plate' => 'F-AC 109',
                'vin' => 'WAUZZZF40PA000109',
                'color' => 'White',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'mileage' => 26700,
                'daily_rate' => 89.00,
                'status' => 'available',
            ],[
                'category' => 'business',
                'brand' => 'Volvo',
                'model' => 'S60',
                'year' => 2024,
                'license_plate' => 'F-AC 110',
                'vin' => 'YV1ZK0000RA000110',
                'color' => 'Dark Blue',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 11200,
                'daily_rate' => 94.00,
                'status' => 'maintenance',
            ],[
                'category' => 'executive',
                'brand' => 'BMW',
                'model' => '5 Series',
                'year' => 2024,
                'license_plate' => 'F-AC 111',
                'vin' => 'WBA53F000RA000111',
                'color' => 'Black',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'mileage' => 8900,
                'daily_rate' => 149.00,
                'status' => 'rented',
            ],[
                'category' => 'executive',
                'brand' => 'Mercedes-Benz',
                'model' => 'E-Class',
                'year' => 2024,
                'license_plate' => 'F-AC 112',
                'vin' => 'W1K2140001A000112',
                'color' => 'Obsidian Black',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 7600,
                'daily_rate' => 159.00,
                'status' => 'available',
            ],[
                'category' => 'executive',
                'brand' => 'Audi',
                'model' => 'A6',
                'year' => 2023,
                'license_plate' => 'F-AC 113',
                'vin' => 'WAUZZZF20PA000113',
                'color' => 'Grey',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'mileage' => 19400,
                'daily_rate' => 149.00,
                'status' => 'reserved',
            ],[
                'category' => 'suv',
                'brand' => 'Volkswagen',
                'model' => 'Tiguan',
                'year' => 2024,
                'license_plate' => 'F-AC 114',
                'vin' => 'WVGZZZ5NZRW000114',
                'color' => 'White',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 5,
                'mileage' => 13200,
                'daily_rate' => 109.00,
                'status' => 'available',
            ],[
                'category' => 'suv',
                'brand' => 'BMW',
                'model' => 'X3',
                'year' => 2024,
                'license_plate' => 'F-AC 115',
                'vin' => 'WBAXW11000P000115',
                'color' => 'Mineral Grey',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'mileage' => 16700,
                'daily_rate' => 129.00,
                'status' => 'rented',
            ],[
                'category' => 'suv',
                'brand' => 'Mercedes-Benz',
                'model' => 'GLC',
                'year' => 2024,
                'license_plate' => 'F-AC 116',
                'vin' => 'W1N2540001A000116',
                'color' => 'White',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 10100,
                'daily_rate' => 139.00,
                'status' => 'available',
            ],[
                'category' => 'suv',
                'brand' => 'Audi',
                'model' => 'Q5',
                'year' => 2023,
                'license_plate' => 'F-AC 117',
                'vin' => 'WAUZZZFY0PA000117',
                'color' => 'Black',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'mileage' => 23100,
                'daily_rate' => 119.00,
                'status' => 'available',
            ],[
                'category' => 'premium-suv',
                'brand' => 'BMW',
                'model' => 'X5',
                'year' => 2024,
                'license_plate' => 'F-AC 118',
                'vin' => 'WBAXCR0000P000118',
                'color' => 'Black Sapphire',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'mileage' => 8400,
                'daily_rate' => 169.00,
                'status' => 'rented',
            ],[
                'category' => 'premium-suv',
                'brand' => 'Mercedes-Benz',
                'model' => 'GLE',
                'year' => 2024,
                'license_plate' => 'F-AC 119',
                'vin' => 'W1N1670001A000119',
                'color' => 'Graphite',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 6900,
                'daily_rate' => 179.00,
                'status' => 'available',
            ],[
                'category' => 'premium-suv',
                'brand' => 'Volvo',
                'model' => 'XC90',
                'year' => 2023,
                'license_plate' => 'F-AC 120',
                'vin' => 'YV1LF0000PA000120',
                'color' => 'Silver',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 7,
                'mileage' => 15800,
                'daily_rate' => 159.00,
                'status' => 'available',
            ],[
                'category' => 'luxury',
                'brand' => 'Mercedes-Benz',
                'model' => 'S-Class',
                'year' => 2024,
                'license_plate' => 'F-AC 121',
                'vin' => 'W1K2230001A000121',
                'color' => 'Obsidian Black',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 4200,
                'daily_rate' => 249.00,
                'status' => 'reserved',
            ],[
                'category' => 'luxury',
                'brand' => 'BMW',
                'model' => '7 Series',
                'year' => 2024,
                'license_plate' => 'F-AC 122',
                'vin' => 'WBA7R00000P000122',
                'color' => 'Black',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'mileage' => 3700,
                'daily_rate' => 259.00,
                'status' => 'available',
            ],[
                'category' => 'luxury',
                'brand' => 'Porsche',
                'model' => 'Panamera',
                'year' => 2023,
                'license_plate' => 'F-AC 123',
                'vin' => 'WP0ZZZ97ZPA000123',
                'color' => 'Guards Red',
                'transmission' => 'automatic',
                'fuel_type' => 'petrol',
                'seats' => 4,
                'mileage' => 9200,
                'daily_rate' => 289.00,
                'status' => 'available',
            ],[
                'category' => 'electric',
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2024,
                'license_plate' => 'F-AC 124',
                'vin' => '5YJ3E00000RA000124',
                'color' => 'Pearl White',
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'seats' => 5,
                'mileage' => 6100,
                'daily_rate' => 99.00,
                'status' => 'available',
            ],[
                'category' => 'electric',
                'brand' => 'Tesla',
                'model' => 'Model Y',
                'year' => 2024,
                'license_plate' => 'F-AC 125',
                'vin' => '7SAYG00000RA000125',
                'color' => 'Midnight Silver',
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'seats' => 5,
                'mileage' => 7800,
                'daily_rate' => 119.00,
                'status' => 'rented',
            ]
        ];
        foreach ($vehicles as $vehicle) {
            $categorySlug = $vehicle['category'];
            unset($vehicle['category']);
            $vehicle['category_id'] = $categories[$categorySlug];
            Vehicle::updateOrCreate(
                ['license_plate' => $vehicle['license_plate']],
                $vehicle
            );
        }
    }
}
